---
.travis.yml:
  user: camptocamp
  secure: "PxFc4SYyoJEPwHxcBnkL2aMwbwHf8kyxPltQqbOQ+HjighHf9vXjJo1RAjpn3YqdR0nTzKuZm4bnwCzA7bFxn9MeZCuNt4qSriPbHfvEm+FXiLPGYniQGcb0BnP+GtT8ZjaJvz2fNDqHagqtjcAkk6bLCFyGTqKs8oJk8uRoh6U="
  branches:
    - master
    - /^\d/
  deploy_to_forge:
    enabled: true
    tag_regex: "^\\d"
Gemfile:
  optional:
    ':development':
      - gem: 'github_changelog_generator'
Rakefile:
  changelog_version_tag_pattern: '%s'
