name         'camptocamp-tomcat'
version      '0.0.2'
dependency   'puppetlabs/stdlib', '0.0.1'
source       'https://github.com/camptocamp/puppet-tomcat'
author       'DevOps Team / Camptocamp'
license      'GNU GPLv3'
summary      'Camptocamp Tomcat Module'
description  'Tomcat Module for Puppet'
project_page 'https://github.com/camptocamp/puppet-tomcat'
